server:
  port: 8989
  context-path: /smallshop
  jsp-servlet:
    init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smallshop
    username: root
    password: root
  http:
    multipart:
      max-request-size: 20971520
      max-file-size: 41943040

mybatis:
  mapper-locations: classpath:daoMappers/*DaoMapper.xml
  type-aliases-package: com.baizhi.entity
